# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: git setup
        # Set up git and export env vars to be used in later steps.
        #   Note the unconventional mechanism for exporting envs by appending to
        #   $GITHUB_ENV.
        id: git-setup
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "WORKDIR=$(pwd)" >> $GITHUB_ENV

      - name: install additional ubuntu pkgs
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev libpng-dev libfontconfig1-dev pandoc

      - name: Setup R for direct install
        uses: r-lib/actions/setup-r@v2
        with:
          # manually setting this here
          r-version: '4.4.2'

      - name: Install dependencies
        run: |
          setRepositories(ind=c(1,2,3,4,5))
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      # uses: r-lib/actions/setup-r-dependencies@v2
      # with:
      #   cache: true
      #   extra-packages: local::.

      #- name: R CMD check
      #  run:
      #    rcmdcheck::rcmdcheck(args="--as-cran --no-manual", error_on="error")
      #  shell: Rscript {0}




